Dsh\NewBundle\Entity\Filmstrip\Photos:
    type: entity
    table: null
    repositoryClass: Dsh\NewBundle\Entity\Filmstrip\PhotosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        photoName:
            type: string
            length: 255
            column: PhotoName
        price:
            type: decimal
            column: Price
        location:
            type: string
            length: 255
            column: Location
        event:
            type: string
            length: 255
            column: Event
        photographer:
            type: string
            length: 255
            column: Photographer
        datetimetaken:
            type: datetimetz
    lifecycleCallbacks: {  }
